### ISSUE TITLE
any Chinese support?

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode-wordcount#6]
It doesn't work well with Chinese
## ![image](https://cloud.githubusercontent.com/assets/7588612/16265310/2fe893d2-38b1-11e6-926c-87319732c6a5.png)

vscode: 1.3.0 - insider
os: win10 build 14367

**Comment by Tyriar** [comment]
@neilsustc I'm curious what you would expect to happen here. I don't know too much about grammatical structures in Chinese but in order to do this would go well beyond just a simple split of `' '` characters and into trying to parse and understand the language? I know for Japanese this would certainly be a non-trivial problem to solve.

Would a simple count of gylphs be better? How would this work when there is a mix of Roman and CJK characters?

/cc @rebornix

**Comment by neilsustc** [comment]
I think *office word* does it really well.

![image](https://cloud.githubusercontent.com/assets/7588612/16288869/d44858f6-3922-11e6-81dd-b231fd87d0f0.png)

Maybe this extension doesn't have to be so powerful.
In Chinese, one character means one "word" (not exactly, but you can just use the count of characters, excluding comma `，`, full stop `。` etc.)
In the above picture, `一` means `one`, `二` means `two`, ...

Thank you!

**Comment by rebornix** [comment]
Chinese characters are [Logograms](https://en.wikipedia.org/wiki/Logogram), which means a written character represents a word or phrase. Besides, CJK characters are written inside a square/rectangle so you don't need a space to separate words or phrases like in English.

Japanese is much more complicated. The modern Japanese writing system is a combination of three character types: logographic kanji, which are adopted Chinese characters; syllabic kana; and the Latin script Alphabet Rōmaji. So we are facing the same issue when we run into Japanese logographic kanji :(

**Comment by yeluoqiuzhi** [comment]
amazing

**Comment by JerryZhongJ** [comment]
Actually, when dealing with Chinese, the only thing needs to do is filtering punctuations out (I guess).
